# Generated by Django 2.0.1 on 2018-02-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('text_description', models.TextField(blank=True, max_length=500)),
                ('img_link', models.URLField(blank=True)),
                ('city', models.TextField(blank=True, max_length=30)),
                ('donor_email', models.EmailField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
