# Generated by Django 2.0.1 on 2018-02-20 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('text_description', models.TextField(blank=True, max_length=500)),
                ('quantity', models.IntegerField(default=0)),
                ('img_link', models.URLField(blank=True)),
                ('city', models.TextField(blank=True, max_length=30)),
                ('donor_email', models.EmailField(max_length=255)),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], default='pending', max_length=100, no_check_for_status=True)),
                ('owner_interest', models.BooleanField(default=False)),
                ('needs_pickup', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.TextField(blank=True, max_length=60)),
                ('text_description', models.TextField(blank=True, max_length=500)),
                ('img_link', models.URLField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
