# Generated by Django 2.0.1 on 2018-04-24 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import mptt.fields
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('text_description', models.TextField(blank=True, max_length=500)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('img_link', models.URLField(blank=True)),
                ('city', models.TextField(blank=True, max_length=30)),
                ('donor_email', models.EmailField(max_length=255)),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], default='pending', max_length=100, no_check_for_status=True)),
                ('owner_interest', models.BooleanField(default=False)),
                ('needs_pickup', models.BooleanField(default=False)),
                ('declined_reason', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Business')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.TextField(blank=True, max_length=60)),
                ('text_description', models.TextField(blank=True, max_length=500)),
                ('img_link', models.URLField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='inventory_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='inventory',
            name='tag_pile',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='item.Inventory_Tags'),
        ),
        migrations.AddField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(blank=True, default=None, to='item.Inventory'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='item.Category'),
        ),
    ]
