# Generated by Django 2.0.1 on 2018-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('text_description', models.TextField(blank=True, max_length=500)),
                ('img_link', models.URLField(blank=True)),
            ],
        ),
    ]
