# Generated by Django 2.0.1 on 2018-02-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tag_pile',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
