# Generated by Django 2.0.1 on 2018-05-31 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20180426_1925'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('text_description', models.TextField(blank=True, max_length=500)),
                ('user_email', models.EmailField(max_length=255)),
                ('status', model_utils.fields.StatusField(choices=[('sent', 'sent'), ('received', 'received')], default='sent', max_length=100, no_check_for_status=True)),
                ('declined_reason', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Business')),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
