# Generated by Django 2.0.1 on 2018-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
