# Generated by Django 2.0.1 on 2018-02-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_inventory_tag_pile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
