# Generated by Django 2.0.1 on 2018-06-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_storelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
    ]
