# Generated by Django 2.0.1 on 2018-02-28 04:05

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20180223_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='tag_pile',
        ),
        migrations.AlterUniqueTogether(
            name='inventory_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='inventory',
            name='tag_pile',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='item.Inventory_Tags'),
        ),
    ]
