# Generated by Django 2.0.1 on 2018-02-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20180216_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
