# Generated by Django 2.0.1 on 2018-03-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(default=None, to='item.Inventory'),
        ),
    ]
