# Generated by Django 2.0.1 on 2018-03-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20180227_2005'),
        ('item', '0005_auto_20180303_0110'),
    ]

    operations = [
    ]
