# Generated by Django 2.0.1 on 2018-02-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20180216_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
