# Generated by Django 2.0.1 on 2018-03-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_merge_20180304_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='declined_reason',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
