# Generated by Django 2.0.1 on 2018-02-17 04:37

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20180217_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='archived',
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True),
        ),
    ]
