# Generated by Django 2.0.1 on 2018-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_donation_owner_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='needs_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
