# Generated by Django 2.0.1 on 2018-04-24 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('owner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='auth.Group')),
            ],
        ),
    ]
