# Generated by Django 2.0.1 on 2018-04-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_key',
            field=models.TextField(default='change_this_key', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
