# Generated by Django 2.0.1 on 2018-06-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180604_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='icon',
            field=models.URLField(blank=True),
        ),
    ]
