# Generated by Django 2.0.1 on 2018-02-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
