# Generated by Django 2.0.1 on 2018-02-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_isowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_key',
        ),
    ]
